ARG FROM_IMAGE_NAME=yellow.hub.cambricon.com/pytorch/pytorch:v1.9.0-torch1.9-ubuntu18.04

FROM ${FROM_IMAGE_NAME}

RUN mkdir /home/pytorch_modelzoo/

COPY ./tools /home/pytorch_modelzoo/tools

COPY ./built-in/cv/detection/PointPillar /home/pytorch_modelzoo/built-in/cv/detection/PointPillar

WORKDIR /home/pytorch_modelzoo/built-in/cv/detection/PointPillar

ENV VIRTUAL_ENV=/torch/venv3/pytorch
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

#RUN source /torch/venv3/pytorch/bin/activate

RUN pip install -r models/requirements.txt
